defaults:
  - model: gant
  - dataset: cora

gpus: 1
num_workers: 0
random_seed: 1590258941

training:
  epochs: 10000
  batch_size: 1
  # checkpointing
  save_ckpts: 10
  monitor: val_loss
  mode: min
  patience: 100

testing:
  checkpoint: 'outputs/2020-07-09/20-19-27/lightning_logs/version_0/checkpoints/epoch=141.ckpt'
  batch_size: 1
  epochs: 1

loss:
  class: torch.nn.CrossEntropyLoss

optimizer:
  class: torch.optim.Adam
  params:
    lr: 5e-3
    weight_decay: 5e-4

metrics:
  - accuracy:
    class: metrics.Accuracy

  - f1:
    class: metrics.F1Score

# set logging paths
hydra:
  run:
    dir: outputs/${model.class}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  sweep:
    dir: outputs/${model.class}/${now:%Y-%m-%d}/${now:%H-%M-%S}/