defaults:
  - model: gat
  - dataset: ppi

gpus: 0
num_workers: 0
random_seed: 1594753342

training:
  epochs: 10000
  batch_size: 2
  # checkpointing
  save_ckpts: 10
  monitor: val_loss
  mode: min
  patience: 200
  accumulate_grad_batches: 1

testing:
  checkpoint: 'outputs/2020-07-09/20-19-27/lightning_logs/version_0/checkpoints/epoch=141.ckpt'
  batch_size: 2
  epochs: 1

loss:
  class: losses.MaskedBCEWithLogitsLoss

optimizer:
  class: torch.optim.Adam
  params:
    lr: 5e-3
    weight_decay: 5e-4

metrics:
  - loss:
    class: losses.MaskedBCEWithLogitsLoss

#  - accuracy:
#    class: metrics.Accuracy
#  - f1:
#    class: metrics.F1Score
