defaults:
  - model: gant
  - dataset: cora

gpus: 1
num_workers: 0
# random seeds used for sweeps:
# 46055786, 412709707, 856211913, 474076048, 285834014
random_seed: 1590258941

training:
  epochs: 10000
  batch_size: 1
  # checkpointing
  save_ckpts: 5
  monitor: val_loss
  mode: min
  patience: 100

testing:
  checkpoint: 'outputs/model.gat.GraphAttentionNeighbourNetwork/2020-07-31/01-29-50/lightning_logs/version_0/checkpoints/epoch=267.ckpt'
  batch_size: 1
  epochs: 1

loss:
  class: torch.nn.CrossEntropyLoss

optimizer:
  class: torch.optim.Adam
  params:
    lr: 5e-3
    weight_decay: 5e-4

metrics:
  - accuracy:
    class: metrics.Accuracy

  - f1:
    class: metrics.F1Score

# set logging paths
hydra:
  run:
    dir: outputs/${model.class}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  sweep:
    dir: outputs/${model.class}/${now:%Y-%m-%d}/${now:%H-%M-%S}/